Corrigindo configuração de Java no workflow

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -30,6 +30,20 @@ jobs:
           google-chrome --version
           chromedriver --version
 
+      - name: Install Compatible ChromeDriver
+        run: |
+          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1)
+          wget -O chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROME_VERSION.0/chromedriver_linux64.zip" || echo "Version not found"
+          if [ -f chromedriver.zip ]; then
+           unzip chromedriver.zip
+          sudo mv chromedriver /usr/bin/chromedriver
+          sudo chmod +x /usr/bin/chromedriver
+          else
+          echo "ChromeDriver version not available. Exiting."
+          exit 1
+          fi
+  
+
       - name: Limpar Diretórios e Processos
         run: |
           pkill -9 chrome || true
